#!/bin/bash
#this is the simple installation script
mkdir -p ~/.jManga/bin
cp ./jManga ~/.jManga/bin
chmod -R 777 ~/.jManga
cp setting.j  ~/.jManga
cp function.j  ~/.jManga
cp variable.j  ~/.jManga

echo 'jManga is installed to ~/.jManga'
echo 'for easier running you can add ~/.jManga/bin to PATH'
